### I package all the code demonstrated in the work flow file into one function. 
### You can simply download the ipynb file and execute the code.

In [5]:
import pandas as pd
import numpy as np
import math

def Option_Value():
    
    # Step 1: Ask user to input the data.
    print("What is the current stock price?")
    S = float(input())
    print("How many folds the stock will increase per peirod if it goes up?")
    u = float(input())
    print("How many folds the stock will decrease per period if it goes down?")
    d = float(input())
    print("What is the continuously compounded riskless rate per period? (% p.a.)")
    r = float(input())/100
    print("What is the strike price")
    X = float(input())
    print("How many periods you would like to consider?")
    n = int(input())
    R=math.exp(r)
    p=(R-d)/(u-d)
    
    
    # Step 2: Build the three different kinds of dataframe to store calculated stock price, call value, and put value.
    ## produce row index for the dataframe
    row_name = list(range(int(n)+1))
    row_name = [x for x in row_name]
    row_name = ['第'+ str(x) +'期' for x in row_name]
    
    ## produce row index for the dataframe
    col_name = list(range(int(n)+1))
    col_name = [x for x in col_name]
    col_name = ['下跌'+ str(x) +'次' for x in col_name]
    
    df_StockPrice = pd.DataFrame(index=row_name, columns=col_name)
    df_StockPrice = df_StockPrice.fillna(0) # with 0s rather than NaNs
    
    df_call = pd.DataFrame(index=row_name, columns=col_name)
    df_call = df_call.fillna(0) # with 0s rather than NaNs
    
    df_put = pd.DataFrame(index=row_name, columns=col_name)
    df_put = df_put.fillna(0) # with 0s rather than NaNs
    
    
    # Step 3: Calculate every possible stock price under different periods
    for i in list(range(len(row_name))):
        for j in list(range(len(row_name))):
            if i<j:
                df_StockPrice.iloc[i,j] = str('NA')
            else:
                df_StockPrice.iloc[i,j] = S*u**(i-j)*d**j
    
    
    # Step 4: Calculate every possible call value under different periods
    for i in reversed(list(range(len(row_name)))):
        for j in reversed(list(range(len(row_name)))):
            if i<j:
                df_call.iloc[i,j] = str('NA')
            else:
                if i == len(row_name)-1:
                    if (S*u**(i-j)*d**j)>X:
                        df_call.iloc[i,j] = (S*u**(i-j)*d**j)-X
                    else:
                        df_call.iloc[i,j] = 0
                else:
                    df_call.iloc[i,j] = (p*df_call.iloc[i+1,j] + (1-p)*df_call.iloc[i+1,j+1])/R
                    
    
    # Step 5: Calculate every possible put value under different periods
    for i in reversed(list(range(len(row_name)))):
        for j in reversed(list(range(len(row_name)))):
            if i<j:
                df_put.iloc[i,j] = str('NA')
            else:
                if i == len(row_name)-1:
                    if (S*u**(i-j)*d**j)<X:
                        df_put.iloc[i,j] = X-(S*u**(i-j)*d**j)
                    else:
                        df_put.iloc[i,j] = 0
                else:
                    df_put.iloc[i,j] = (p*df_put.iloc[i+1,j] + (1-p)*df_put.iloc[i+1,j+1])/R
                    
    
    # Step 6: Display results
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', None)
    print("\n Under BOPM, possible stock price under different periods show as below:")
    display(df_StockPrice)
    
    print("\n Under BOPM, possible option values under different periods show as below:")
    display(df_call)
    
    print("\n Under BOPM, possible put values under different periods show as below:")
    display(df_put)

In [7]:
Option_Value()

What is the current stock price?
160
How many folds the stock will increase per peirod if it goes up?
1.5
How many folds the stock will decrease per period if it goes down?
0.5
What is the continuously compounded riskless rate per period? (% p.a.)
18.232
What is the strike price
150
How many periods you would like to consider?
3

 Under BOPM, possible stock price under different periods show as below:

      下跌0次 下跌1次 下跌2次 下跌3次
第0期  160.0   NA   NA   NA
第1期  240.0   80   NA   NA
第2期  360.0  120   40   NA
第3期  540.0  180   60   20

 Under BOPM, possible option values under different periods show as below:

           下跌0次     下跌1次 下跌2次 下跌3次
第0期   85.069229       NA   NA   NA
第1期  141.458097  10.2083   NA   NA
第2期  234.999805     17.5    0   NA
第3期  390.000000       30    0    0

 Under BOPM, possible put values under different periods show as below:

          下跌0次     下跌1次     下跌2次 下跌3次
第0期  11.875190       NA       NA   NA
第1期   5.625088  34.3753       NA   NA
第2期   0.000000  22.5002  85.0002   NA
第3期   0.000000        0       90  130